modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ore_pack"
version="2.02"
displayName="Ore pack"
displayURL="https://cccstudiocoder.github.io"
logoFile="logo.png"
credits="Created using mod maker MCreator - thanks to Pylo"
authors="CCC Studio"
description="Five new ores for you !"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ore_pack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration